version: '2'

services:
  tor:
    build: ./tor/
    restart: unless-stopped
    volumes:
      - tor-control:/var/lib/tor/
  
  coredns:
    build: .
    restart: unless-stopped
    ports:
      - 55553:55553/udp
      - 55553:55553/tcp
    links:
      - tor
    depends_on:
      - tor
    volumes_from:
      - tor
    volumes:
      - ./Corefile:/Corefile:ro
    command: [ "-conf", "/Corefile"]

volumes:
  tor-control: